version: '3.7'
services:
  rest-api:
    container_name: 'rest-api'
    build: rest-api
    restart: on-failure
    ports:
      - '5000:5000'
    depends_on:
      - prometheus
      - grafana
    networks:
      tracker-network:

  prometheus:
    container_name: 'prometheus'
    build: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - grafana
    networks:
      tracker-network:

  grafana:
    container_name: 'grafana'
    build: grafana
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
    networks:
      tracker-network:

volumes:
  grafana-storage:

networks:
  tracker-network:
    external:
      name: br0a

