apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
      containers:
      - image: grafana
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
        envFrom:
          - configMapRef:
              name: env-variables
        imagePullPolicy: IfNotPresent
        name: grafana
      restartPolicy: Always
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-22T10:10:38Z"
    lastUpdateTime: "2020-04-22T10:10:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-22T10:10:32Z"
    lastUpdateTime: "2020-04-22T10:10:38Z"
    message: ReplicaSet "grafana-6d98d9c484" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
