apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prometheus
        envFrom:
          - configMapRef:
              name: env-variables
        imagePullPolicy: IfNotPresent
        name: prometheus
      restartPolicy: Always
