apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
spec:
  storageClassName: local
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"