apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-22T07:39:29Z"
  labels:
    app: rest-api
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":5000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-04-22T07:39:29Z"
  name: rest-api
  namespace: default
  resourceVersion: "8965"
  selfLink: /api/v1/namespaces/default/services/rest-api
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32580
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rest-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
