apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-api
  name: rest-api
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32580
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rest-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
