apiVersion: v1
data:
  GRAFANA_HOST: grafana
  GRAFANA_PORT: "3000"
  REST_API_HOST: rest-api
  REST_API_PORT: "5000"
  GF_SECURITY_ADMIN_PASSWORD: P@assword
  PROMETHEUS_HOST: prometheus
  PROMETHEUS_PORT: "9000"
kind: ConfigMap
metadata:
  name: env-variables
  selfLink: /api/v1/namespaces/default/configmaps/env-variables